# Generated by Django 5.0.3 on 2024-03-15 16:42

import Staff.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='staff', max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Staff.models.upload_image_to)),
                ('title', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('remote', 'remote'), ('parttime', 'parttime'), ('office', 'office')], max_length=100, null=True)),
                ('vaccancies', models.IntegerField(null=True)),
                ('package', models.CharField(max_length=100, null=True)),
                ('experiance', models.FloatField(default=0, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('qualifications', models.JSONField(default=Staff.models.default_qualifications)),
                ('responsibility', models.JSONField(default=Staff.models.default_responsibility)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='Staff.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyedJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.studentmodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.jobsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SaveJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.jobsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.studentmodel')),
            ],
        ),
    ]
