# Generated by Django 5.0.3 on 2024-03-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsmodel',
            name='qualifications',
        ),
    ]
