# Generated by Django 5.0.3 on 2024-03-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_jobsmodel_experiance'),
        ('User', '0003_remove_studentmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyedJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.jobsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.studentmodel')),
            ],
        ),
    ]
