# Generated by Django 5.0.3 on 2024-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_applyedjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyedjobmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
