# Generated by Django 5.0.3 on 2024-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_applyedjobmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsmodel',
            old_name='requirements',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Enter multiple values separated by commas.', null=True),
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='responsibility',
            field=models.TextField(blank=True, help_text='Enter multiple values separated by commas.', null=True),
        ),
    ]
