# Generated by Django 5.0.3 on 2024-03-13 09:10

import Staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_rename_requirements_jobsmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=Staff.models.upload_image_to),
        ),
    ]
