# Generated by Django 5.0.3 on 2024-03-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_jobsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
