# Generated by Django 5.0.3 on 2024-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_companymodel_alter_jobsmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='user_type',
            field=models.CharField(default='staff', max_length=50),
        ),
    ]
