# Generated by Django 5.0.3 on 2024-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_companymodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='experiance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='type',
            field=models.CharField(choices=[('remote', 'remote'), ('parttime', 'parttime'), ('office', 'office')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='vaccancies',
            field=models.IntegerField(null=True),
        ),
    ]
