# Generated by Django 5.0.3 on 2024-03-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_alter_jobsmodel_description_and_more'),
        ('User', '0007_studentmodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.jobsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.studentmodel')),
            ],
        ),
    ]
