# Generated by Django 5.0.3 on 2024-03-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0011_savejobmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsmodel',
            name='saved',
        ),
    ]
