# Generated by Django 5.0.3 on 2024-03-07 17:51

import User.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('CSE', 'COMPUER SCIENCE AND ENGINERRING'), ('ECE', 'ELECTIC AND COMMUNICATION ENGINEERING'), ('MECH', 'MECHANICAL ENGINEERING'), ('CIVIL', 'CIVIL ENGINEERING'), ('OTHER', 'OTHER')], max_length=60, null=True)),
                ('ten_certificate', models.FileField(null=True, upload_to=User.models.upload_certificate_to)),
                ('plustwo_certificate', models.FileField(null=True, upload_to=User.models.upload_certificate_to)),
                ('resume', models.FileField(null=True, upload_to=User.models.upload_resume_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
