# Generated by Django 5.0.3 on 2024-03-15 16:42

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='skills',
            field=models.JSONField(default=User.models.default_skill),
        ),
    ]
