# Generated by Django 5.0.3 on 2024-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
