# Generated by Django 5.0.3 on 2024-03-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_studentmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
    ]
