# Generated by Django 5.0.3 on 2024-03-12 16:06

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_studentmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=User.models.upload_image_to),
        ),
    ]
