# Generated by Django 5.0.3 on 2024-03-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_studentmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter multiple values separated by commas.', null=True),
        ),
    ]
