# Generated by Django 5.0.3 on 2024-03-13 06:19

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_studentmodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='degree_certificate',
            field=models.FileField(null=True, upload_to=User.models.upload_certificate_to),
        ),
    ]
