# Generated by Django 5.0.3 on 2024-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_studentmodel_degree_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='user_type',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
